package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList<String>(1);
    _jspx_dependants.add("/hfooter.html");
  }

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write('\n');
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("To change this license header, choose License Headers in Project Properties.\r\n");
      out.write("To change this template file, choose Tools | Templates\r\n");
      out.write("and open the template in the editor.\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css\">\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        .bs-example {\r\n");
      out.write("      margin: 0px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand {\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      font-family: sans-serif;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .footer {\r\n");
      out.write("  \r\n");
      out.write("   left: 0;\r\n");
      out.write("   bottom: 0;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   background-color: #FF0018;\r\n");
      out.write("   color: white;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   height:50px;\r\n");
      out.write("        .xyz{\r\n");
      out.write("          margin-bottom: 0px;\r\n");
      out.write("        \r\n");
      out.write("          background-size: cover;\r\n");
      out.write("          background-repeat: no-repeat;\r\n");
      out.write("        }\r\n");
      out.write("      </style>\r\n");
      out.write("      \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"bs-example\">\r\n");
      out.write("    <nav style=\"background-color: #FF0018;\" class=\"navbar navbar-expand-md navbar-dark fixed-top\">\r\n");
      out.write("      <a href=\"/\" class=\"navbar-brand\"><i class=\"fas fa-heartbeat\"></i>&nbsp; Blood Bank Management</a>\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"collapse navbar-collapse justify-content-between\" id=\"navbarCollapse\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-collapse collapse w-100 order-3 dual-collapse2\">\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"patientHome.jsp\"><i class=\"fas fa-home\"></i>&nbsp; Home</i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"patientLogin.jsp\"><i class=\"fas fa-procedures\"></i>&nbsp; Patient</i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"donorLogin.jsp\"><i class=\"fas fa-user\"></i>&nbsp; Donor</i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"adminLogin.jsp\"><i class=\"fas fa-user-shield\"></i>&nbsp; Admin</i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </div> \r\n");
      out.write("    <br><br><br> <br><br><br> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write(" <link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" media=\"screen\">\n");
      out.write("<style>\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400&display=swap');\n");
      out.write("            #wrapper\n");
      out.write("            {\n");
      out.write("                width:100%;\n");
      out.write("                height:800px;\n");
      out.write("                //border:1px solid white;\n");
      out.write("                margin:0 auto;\n");
      out.write("            }\n");
      out.write("           \n");
      out.write("            #parent\n");
      out.write("            {\n");
      out.write("                width:100%;\n");
      out.write("                height:700px;\n");
      out.write("                margin-top:-90px;\n");
      out.write("                \n");
      out.write("            }\n");
      out.write("             \n");
      out.write("         #main\n");
      out.write("         {\n");
      out.write("             width:100%;\n");
      out.write("             height:500px;\n");
      out.write("             background-color:gray;\n");
      out.write("             text-align: center;\n");
      out.write("             float:right;\n");
      out.write("             \n");
      out.write("         }\n");
      out.write("         body {\n");
      out.write("  \n");
      out.write("              margin: 0;\n");
      out.write("              // line-height: 1.5;\n");
      out.write("              //font-family: 'poppins',sans-serif;\n");
      out.write("             }\n");
      out.write("\n");
      out.write("        html {\n");
      out.write("             box-sizing: border-box;\n");
      out.write("             }\n");
      out.write("\n");
      out.write("          *, *:before, *:after {\n");
      out.write("             box-sizing: inherit;\n");
      out.write("              }\n");
      out.write("\n");
      out.write("        .column {\n");
      out.write("             float: left;\n");
      out.write("             width: 33.3%;\n");
      out.write("             margin-bottom: 16px;\n");
      out.write("             padding: 0 8px;\n");
      out.write("             }\n");
      out.write("\n");
      out.write("        .card {\n");
      out.write("              box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);\n");
      out.write("              margin: 8px;\n");
      out.write("              }\n");
      out.write("\n");
      out.write("        .about-section {\n");
      out.write("               padding: 50px;\n");
      out.write("               text-align: center;\n");
      out.write("               background-color:#474e5d;\n");
      out.write("               background-image:url(images/k.gif);\n");
      out.write("               \n");
      out.write("               color: white;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("             padding: 0 16px;\n");
      out.write("  \n");
      out.write("            }\n");
      out.write("\n");
      out.write("        .container::after, .row::after {\n");
      out.write("             content: \"\";\n");
      out.write("             clear: both;\n");
      out.write("             display: table;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        .title {\n");
      out.write("             color: grey;\n");
      out.write("             }\n");
      out.write("\n");
      out.write("        .button {\n");
      out.write("              border: none;\n");
      out.write("              outline: 0;\n");
      out.write("              display: inline-block;\n");
      out.write("              padding: 8px;\n");
      out.write("              color: white;\n");
      out.write("              background-color:black;\n");
      out.write("              text-align: center;\n");
      out.write("              cursor: pointer;\n");
      out.write("              width: 100%;\n");
      out.write("             }\n");
      out.write("\n");
      out.write("        .button:hover {\n");
      out.write("              background-color: #555;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        @media screen and (max-width: 650px) {\n");
      out.write("         .column {\n");
      out.write("                width: 100%;\n");
      out.write("                display: block;\n");
      out.write("                 }\n");
      out.write("               }\n");
      out.write("            \n");
      out.write("            /*body{\n");
      out.write("                line-height: 1.5;\n");
      out.write("                font-family: 'poppins',sans-serif;\n");
      out.write("            }*/\n");
      out.write("           \n");
      out.write("            \n");
      out.write("           \n");
      out.write("                \n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("     <body bgcolor=\"grey\" onload=\"moveslider()\">\n");
      out.write("        <div id=\"wrapper\" style=\"width:100%;\">\n");
      out.write("          \n");
      out.write("            \n");
      out.write("            \n");
      out.write("          \n");
      out.write("            <div id=\"parent\">\n");
      out.write("                \n");
      out.write("                <div id=\"main\">\n");
      out.write("                    <div class=\"about-section\">\n");
      out.write("  <h1>ABOUT US...</h1>\n");
      out.write("  <p>Blood Bank Management System is a Very useful app for the today' s life of human being. This proposed system provides online storage/ updations and retrieval facility. This system promises very less or no paper work and also provides help to blood recipient, blood banks and donors also. In this system everything is stored electronically so very less amount of paper work is required and information can be retrieved very easily without searching here and there into registers. This project plays as a vital role in saving life of human beings and which is also its main aim. The project Blood Bank Management System is developed so that users can view the information about registered blood donors such as name, address, and other such personal information along with their details of blood group and other medical information of donor</p>\n");
      out.write("  \n");
      out.write("  <a href=\"https://en.wikipedia.org/wiki/Blood_bank\"><h3 style=\"color:lightskyblue\">KNOW MORE......!</h3></a>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("\n");
      out.write("<h2 style=\"text-align:center\">Connection With Hospitals</h2>\n");
      out.write("<div class=\"row\">\n");
      out.write("  <div class=\"column\">\n");
      out.write("    <div class=\"card\">\n");
      out.write("      <img src=\"images/9.jpg\" alt=\"Hospital 1\" style=\"width:100%\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <h2>Community Hospitals</h2>\n");
      out.write("        <p class=\"title\">Hospital 1</p>\n");
      out.write("        <p>Non-teaching hospitals serving local communities without federal funding are known as community hospitals. They can be \n");
      out.write("            found in rural or urban settings and provide vital services to their local populations. The American Hospital Association reports 4,840 hospitals in the U.S. today.</p>\n");
      out.write("        <p>h1@example.com</p>\n");
      out.write("        <p><button class=\"button\">Contact</button></p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"column\">\n");
      out.write("    <div class=\"card\">\n");
      out.write("      <img src=\"images/10.jpg\" alt=\"Hospital 2\" style=\"width:100%\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <h2>District Hospitals</h2>\n");
      out.write("        <p class=\"title\">Hospital 2</p>\n");
      out.write("        <p>District hospitals serve as healthcare hubs for their geographic regions. They have more extensive intensive care facilities and long-term care programs in addition to providing necessary \n");
      out.write("            treatments in fields like obstetrics, general surgery, plastic surgery and more.</p>\n");
      out.write("        <p>h2@example.com</p>\n");
      out.write("        <p><button class=\"button\">Contact</button></p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"column\">\n");
      out.write("    <div class=\"card\">\n");
      out.write("      <img src=\"images/11.jpg\" alt=\"Hospital 3\" style=\"width:100%\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <h2>Federal Hospitals</h2>\n");
      out.write("        <p class=\"title\">Hospital 3</p>\n");
      out.write("        <p>Sometimes referred to as government hospitals, federal hospitals receive funding from the federal government. In the United States, federally funded hospitals typically handle the healthcare and medical needs of select populations such as Native Americans and Veterans.</p>\n");
      out.write("        <p>h3@example.com</p>\n");
      out.write("        <p><button class=\"button\">Contact</button></p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("        \n");
      out.write("    \n");
      out.write("                <footer class=\"footer\">\n");
      out.write("                    \n");
      out.write("                    <h5 style=\"text-align :center\">Blood Bank Management System@2022</font></h5>\n");
      out.write("               \n");
      out.write("                </footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("           \n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("</body>\n");
      out.write("</html");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
