package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>ADMIN</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css\">\n");
      out.write("    <style>\n");
      out.write("        .container{\n");
      out.write("          margin-top: 20px;\n");
      out.write("          margin-right: 90px;\n");
      out.write("        }\n");
      out.write("        .row{\n");
      out.write("        padding:10px;\n");
      out.write("    }\n");
      out.write("    .fa-tint{     \n");
      out.write("        color: red;    \n");
      out.write("    }\n");
      out.write("    .blood{\n");
      out.write("        float: right;\n");
      out.write("    }\n");
      out.write("    .fa-users{     \n");
      out.write("        color: blue; \n");
      out.write("        font-size: 3ex;   \n");
      out.write("    }\n");
      out.write("    .fa-spinner{     \n");
      out.write("        color: blue; \n");
      out.write("        font-size: 3ex;   \n");
      out.write("    }\n");
      out.write("    .fa-check-circle{     \n");
      out.write("        color: blue; \n");
      out.write("        font-size: 3ex;   \n");
      out.write("    }\n");
      out.write("    .xyz{     \n");
      out.write("        color: blue; \n");
      out.write("        font-size: 3ex;   \n");
      out.write("    }\n");
      out.write("\n");
      out.write("*{\n");
      out.write("  margin: 0;\n");
      out.write("  padding: 0;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("  list-style: none;\n");
      out.write("  text-decoration: none;\n");
      out.write("  font-family: 'Josefin Sans', sans-serif;\n");
      out.write(" \n");
      out.write("}\n");
      out.write("\n");
      out.write("body{\n");
      out.write("   background-color: #f3f5f9;\n");
      out.write("}\n");
      out.write(".bg-danger {\n");
      out.write("    background-color: #ff0018!important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper{\n");
      out.write("  display: flex;\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .sidebar{\n");
      out.write("  width: 200px;\n");
      out.write("  height: 100%;\n");
      out.write("  background: \t#343a40;\n");
      out.write("  padding: 30px 0px;\n");
      out.write("  position: fixed;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .sidebar h2{\n");
      out.write("  color: #fff;\n");
      out.write("  text-transform: uppercase;\n");
      out.write("  text-align: center;\n");
      out.write("  margin-bottom: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .sidebar ul li{\n");
      out.write("  padding: 15px;\n");
      out.write("  border-bottom: 1px solid #bdb8d7;\n");
      out.write("  border-bottom: 1px solid rgba(0,0,0,0.05);\n");
      out.write("  border-top: 1px solid rgba(255,255,255,0.05);\n");
      out.write("}    \n");
      out.write("\n");
      out.write(".wrapper .sidebar ul li a{\n");
      out.write("  color: #bdb8d7;\n");
      out.write("  display: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .sidebar ul li a .fas{\n");
      out.write("  width: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .sidebar ul li:hover{\n");
      out.write("  background-color: #594f8d;\n");
      out.write("}\n");
      out.write("    \n");
      out.write(".wrapper .sidebar ul li:hover a{\n");
      out.write("  color: #fff;\n");
      out.write("}\n");
      out.write(" \n");
      out.write(".wrapper .sidebar .social_media{\n");
      out.write("  position: absolute;\n");
      out.write("  bottom: 0;\n");
      out.write("  left: 50%;\n");
      out.write("  transform: translateX(-50%);\n");
      out.write("  display: flex;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .sidebar .social_media a{\n");
      out.write("  display: block;\n");
      out.write("  width: 40px;\n");
      out.write("  background: #594f8d;\n");
      out.write("  height: 40px;\n");
      out.write("  line-height: 45px;\n");
      out.write("  text-align: center;\n");
      out.write("  margin: 0 5px;\n");
      out.write("  color: #bdb8d7;\n");
      out.write("  border-top-left-radius: 5px;\n");
      out.write("  border-top-right-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .main_content{\n");
      out.write("  width: 100%;\n");
      out.write("  margin-left: 200px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .main_content .header{\n");
      out.write("  padding: 20px;\n");
      out.write("  background: #fff;\n");
      out.write("  color: #717171;\n");
      out.write("  border-bottom: 1px solid #e0e4e8;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .main_content .info{\n");
      out.write("  margin: 20px;\n");
      out.write("  color: #717171;\n");
      out.write("  line-height: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .main_content .info div{\n");
      out.write("  margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-height: 500px){\n");
      out.write("  .social_media{\n");
      out.write("    display: none !important;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write(".fa-sign-out-alt{\n");
      out.write("    color: white;\n");
      out.write("    font-size: 2ex;\n");
      out.write("}\n");
      out.write(".footer {\n");
      out.write("  \n");
      out.write("   left: 0;\n");
      out.write("   bottom: 0;\n");
      out.write("   width: 100%;\n");
      out.write("   background-color: #FF0018;\n");
      out.write("   color: white;\n");
      out.write("   text-align: center;\n");
      out.write("   height:75px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("    \n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("     <nav class=\"navbar navbar-expand-lg navbar-light fixed-top bg-danger\">\n");
      out.write("        <a style=\"color:white;\" class=\"navbar-brand\" href=\"/\"><i class=\"fab fa-gratipay\"></i>&nbsp;<font face = \"Comic sans MS\" size =\"4\">Welcome to admin Home</font></a>\n");
      out.write("        \n");
      out.write("      \n");
      out.write("        <div class=\"navbar-collapse collapse w-100 order-3 dual-collapse2\">\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"logout.jsp\">Logout &nbsp; <i class=\"fas fa-sign-out-alt\"></i></a>\n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("<br><br>\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("    <div class=\"sidebar\">\n");
      out.write("        \n");
      out.write("        <ul>\n");
      out.write("            <li><a style=\"text-decoration:none;\" href=\"adminHome.jsp\"><i class=\"fas fa-home\"></i>Home</a></li>\n");
      out.write("            <li><a style=\"text-decoration:none;\" href=\"adminDonor.jsp\"><i class=\"fas fa-user\"></i>Donor</a></li>\n");
      out.write("            <li><a style=\"text-decoration:none;\" href=\"adminPatient.jsp\"><i class=\"fas fa-user-injured\"></i>Patient</a></li>\n");
      out.write("            <li><a style=\"text-decoration:none;\" href=\"manageStock.jsp\"><i class=\"fas fa-hand-holding-water\"></i>Blood Stock</a></li>\n");
      out.write("           \n");
      out.write("        </ul> \n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("   \n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-sm-3\">\n");
      out.write("          <div class=\"card bg-light\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("                <div class=\"blood\">\n");
      out.write("                    <h2><a href=\"manageStock.jsp\" >A+ </a><i class=\"fas fa-tint\" style=\"color:red\"></i></h2>\n");
      out.write("                </div><br><br>\n");
      out.write("                <div>\n");
      out.write("                   \n");
      out.write("                </div>                            \n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div><br><br><br>\n");
      out.write("        <div class=\"col-sm-3\">\n");
      out.write("            <div class=\"card bg-light\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <div class=\"blood\">\n");
      out.write("                        <h2><a href=\"manageStock.jsp\" >B+ </a><i class=\"fas fa-tint\" style=\"color:red\"></i></h2>\n");
      out.write("                    </div><br><br>\n");
      out.write("                    <div>\n");
      out.write("                        \n");
      out.write("                    </div>                            \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("        </div><br><br>\n");
      out.write("        <div class=\"col-sm-3\">\n");
      out.write("            <div class=\"card bg-light\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <div class=\"blood\">\n");
      out.write("                        <h2><a href=\"manageStock.jsp\" >O+</a><i class=\"fas fa-tint\" style=\"color:red\"></i></h2>\n");
      out.write("                    </div><br><br>\n");
      out.write("                    <div>\n");
      out.write("                    </div>                            \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-sm-3\">\n");
      out.write("            <div class=\"card bg-light\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <div class=\"blood\">\n");
      out.write("                        <h2><a href=\"manageStock.jsp\" >AB+</a><i class=\"fas fa-tint\" style=\"color:red\"></i></h2>\n");
      out.write("                    </div><br><br>\n");
      out.write("                    <div>\n");
      out.write("                        \n");
      out.write("                    </div>                            \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("  \n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-sm-3\">\n");
      out.write("          <div class=\"card bg-light\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("                <div class=\"blood\">\n");
      out.write("                    <h2><a href=\"manageStock.jsp\" >A-</a><i class=\"fas fa-tint\" style=\"color:red\"></i></h2>\n");
      out.write("                </div><br><br>\n");
      out.write("                <div>\n");
      out.write("                    \n");
      out.write("                </div>                            \n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-sm-3\">\n");
      out.write("            <div class=\"card bg-light\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <div class=\"blood\">\n");
      out.write("                        <h2><a href=\"manageStock.jsp\" >B-</a><i class=\"fas fa-tint\" style=\"color:red\"></i></h2>\n");
      out.write("                    </div><br><br>\n");
      out.write("                    <div>\n");
      out.write("                        \n");
      out.write("                    </div>                            \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-sm-3\">\n");
      out.write("            <div class=\"card bg-light\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <div class=\"blood\">\n");
      out.write("                        <h2><a href=\"manageStock.jsp\" >O-</a><i class=\"fas fa-tint\" style=\"color:red\"></i></h2>\n");
      out.write("                    </div><br><br>\n");
      out.write("                    <div>\n");
      out.write("                        \n");
      out.write("                    </div>                            \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-sm-3\">\n");
      out.write("            <div class=\"card bg-light\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <div class=\"blood\">\n");
      out.write("                        <h2><a href=\"manageStock.jsp\" >AB-</a><i class=\"fas fa-tint\" style=\"color:red\"></i></h2>\n");
      out.write("                    </div><br><br>\n");
      out.write("                    <div>\n");
      out.write("                        \n");
      out.write("                    </div>                            \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("<hr>\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"col-sm-3\">\n");
      out.write("        <div class=\"card bg-light\">\n");
      out.write("          <div class=\"card-body\">\n");
      out.write("              <div class=\"blood\">\n");
      out.write("                  <i class=\"fas fa-users\" style=\"color:blue\"></i>\n");
      out.write("              </div><br>\n");
      out.write("              <div>\n");
      out.write("                  <a href=\"editDeleteList.jsp\">Total Donors </a><br>\n");
      out.write("                  \n");
      out.write("              </div>                            \n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-sm-3\">\n");
      out.write("          <div class=\"card bg-light\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                  <div class=\"blood\">\n");
      out.write("                      <i class=\"fas fa-spinner\" style=\"color: blue\"></i>\n");
      out.write("                  </div><br>\n");
      out.write("                  <div>\n");
      out.write("                      <a href=\"adminPatient.jsp\">Total Requests</a> <br>\n");
      out.write("                     \n");
      out.write("                  </div>                            \n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-sm-3\">\n");
      out.write("          <div class=\"card bg-light\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                  <div class=\"blood\">\n");
      out.write("                      <i class=\"far fa-check-circle\" style=\"color: blue\"></i>\n");
      out.write("                  </div><br>\n");
      out.write("                  <div>\n");
      out.write("                      Approved Requests <br>\n");
      out.write("                      \n");
      out.write("                  </div>                            \n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-sm-3\">\n");
      out.write("          <div class=\"card bg-light\">\n");
      out.write("              <div class=\"card-body\">\n");
      out.write("                  <div class=\"blood\">\n");
      out.write("                      <i class=\"fas fa-tint xyz\" style=\"color: blue\"></i>\n");
      out.write("                  </div><br>\n");
      out.write("                  <div>\n");
      out.write("                      \n");
      out.write("                      <a href=\"totalBloodUnit.jsp\">Total Blood Unit (in ml)</a> <br>\n");
      out.write("                  \n");
      out.write("                  </div>                            \n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <h4><center><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>\n");
      out.write("       \n");
      out.write("<div class=\"footer\">\n");
      out.write("  <p>Blood Bank Management System\n");
      out.write("      <br>\n");
      out.write("      Made In India &copy; 2022\n");
      out.write("  </p>\n");
      out.write("</div>  </center></h4>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
