package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class patientLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList<String>(1);
    _jspx_dependants.add("/hfooter.html");
  }

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write('\n');
      out.write('\n');
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("To change this license header, choose License Headers in Project Properties.\r\n");
      out.write("To change this template file, choose Tools | Templates\r\n");
      out.write("and open the template in the editor.\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.css\">\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        .bs-example {\r\n");
      out.write("      margin: 0px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand {\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      font-family: sans-serif;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .footer {\r\n");
      out.write("  \r\n");
      out.write("   left: 0;\r\n");
      out.write("   bottom: 0;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   background-color: #FF0018;\r\n");
      out.write("   color: white;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   height:50px;\r\n");
      out.write("        .xyz{\r\n");
      out.write("          margin-bottom: 0px;\r\n");
      out.write("        \r\n");
      out.write("          background-size: cover;\r\n");
      out.write("          background-repeat: no-repeat;\r\n");
      out.write("        }\r\n");
      out.write("      </style>\r\n");
      out.write("      \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"bs-example\">\r\n");
      out.write("    <nav style=\"background-color: #FF0018;\" class=\"navbar navbar-expand-md navbar-dark fixed-top\">\r\n");
      out.write("      <a href=\"/\" class=\"navbar-brand\"><i class=\"fas fa-heartbeat\"></i>&nbsp; Blood Bank Management</a>\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"collapse navbar-collapse justify-content-between\" id=\"navbarCollapse\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-collapse collapse w-100 order-3 dual-collapse2\">\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"index.jsp\"><i class=\"fas fa-home\"></i>&nbsp; Home</i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"patientLogin.jsp\"><i class=\"fas fa-procedures\"></i>&nbsp; Patient</i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"donorLogin.jsp\"><i class=\"fas fa-user\"></i>&nbsp; Donor</i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"adminLogin.jsp\"><i class=\"fas fa-user-shield\"></i>&nbsp; Admin</i></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </div> \r\n");
      out.write("    <br><br><br> <br><br><br> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write(" <link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" media=\"screen\">\n");
      out.write(" <link rel=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css\">\n");
      out.write(" <style>\n");
      out.write("     /* Importing fonts from Google */\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');\n");
      out.write("\n");
      out.write("/* Reseting */\n");
      out.write("* {\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    font-family: 'Poppins', sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("    background: #ecf0f3;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper {\n");
      out.write("    max-width: 350px;\n");
      out.write("    min-height: 500px;\n");
      out.write("    margin: 80px auto;\n");
      out.write("    padding: 40px 30px 30px 30px;\n");
      out.write("    background-color: #ecf0f3;\n");
      out.write("    border-radius: 15px;\n");
      out.write("    box-shadow: 13px 13px 20px #cbced1, -13px -13px 20px #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logo {\n");
      out.write("    width: 80px;\n");
      out.write("    margin: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logo img {\n");
      out.write("    width: 100%;\n");
      out.write("    height: 80px;\n");
      out.write("    object-fit: cover;\n");
      out.write("    border-radius: 50%;\n");
      out.write("    box-shadow: 0px 0px 3px #5f5f5f,\n");
      out.write("        0px 0px 0px 5px #ecf0f3,\n");
      out.write("        8px 8px 15px #a7aaa7,\n");
      out.write("        -8px -8px 15px #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .name {\n");
      out.write("    font-weight: 600;\n");
      out.write("    font-size: 1.4rem;\n");
      out.write("    letter-spacing: 1.3px;\n");
      out.write("    padding-left: 10px;\n");
      out.write("    color: #555;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .form-field input {\n");
      out.write("    width: 100%;\n");
      out.write("    display: block;\n");
      out.write("    border: none;\n");
      out.write("    outline: none;\n");
      out.write("    background: none;\n");
      out.write("    font-size: 1.2rem;\n");
      out.write("    color: #666;\n");
      out.write("    padding: 10px 15px 10px 10px;\n");
      out.write("    /* border: 1px solid red; */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .form-field {\n");
      out.write("    padding-left: 10px;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .form-field .fas {\n");
      out.write("    color: #555;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .btn {\n");
      out.write("    box-shadow: none;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 40px;\n");
      out.write("    background-color: red;\n");
      out.write("    color: #fff;\n");
      out.write("    border-radius: 25px;\n");
      out.write("    box-shadow: 3px 3px 3px #b1b1b1,\n");
      out.write("        -3px -3px 3px #fff;\n");
      out.write("    letter-spacing: 1.3px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper .btn:hover {\n");
      out.write("    background-color: green;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper a {\n");
      out.write("    text-decoration: none;\n");
      out.write("    font-size: 0.8rem;\n");
      out.write("    color: #03A9F4;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".wrapper a:hover {\n");
      out.write("    color: #039BE5;\n");
      out.write("}\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("@media(max-width: 380px) {\n");
      out.write("    .wrapper {\n");
      out.write("        margin: 30px 20px;\n");
      out.write("        padding: 40px 15px 15px 15px;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write(" \n");
      out.write("    .footer {\n");
      out.write("  \n");
      out.write("   left: 0;\n");
      out.write("   bottom: 0;\n");
      out.write("   width: 100%;\n");
      out.write("   background-color: #FF0018;\n");
      out.write("   color: white;\n");
      out.write("   text-align: center;\n");
      out.write("   height:50px;\n");
      out.write("}    \n");
      out.write(" </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"wrapper\">\n");
      out.write("        <div class=\"logo\">\n");
      out.write("            <i class=\"fa fa-user-shield fa-5x\" style=\"\"></i>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"text-center mt-4 name\">\n");
      out.write("            Patient Login \n");
      out.write("        </div>\n");
      out.write("        <form class=\"p-3 mt-3\" action=\"patientLoginAction.jsp\" method=\"post\">\n");
      out.write("            <div class=\"form-field d-flex align-items-center\">\n");
      out.write("                <span class=\"far fa-user\"></span>\n");
      out.write("                <input type=\"text\" name=\"emailaddress\" id=\"Username\" placeholder=\"Username\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-field d-flex align-items-center\">\n");
      out.write("                <span class=\"fas fa-key\"></span>\n");
      out.write("                <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Password\">\n");
      out.write("            </div>\n");
      out.write("            <label>Enter Captcha:</label>\n");
      out.write("      <div class=\"form-row\">\n");
      out.write("        <div class=\"form-group col-md-6\">\n");
      out.write("            <input type=\"text\" class=\"form-control\" readonly id=\"capt\" required>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"form-group col-md-6\">\n");
      out.write("          <input type=\"text\" class=\"form-control\" id=\"textinput\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("            <h6>Captcha not visible <img src=\"images/refresh.jpg\" style=\"width:30px;height:30px\"  onclick=\"cap()\"></h6>\n");
      out.write("\n");
      out.write("       \n");
      out.write("           <div class=\"form-group\" style=\"text-align:center\"></div>\n");
      out.write("            <button class=\"btn mt-3\">Login</button>\n");
      out.write("            <br><br>\n");
      out.write("           \n");
      out.write("            <div class=\"text-center fs-6\">\n");
      out.write("            <a>New User</a>     <a href=\"registration.jsp\">Registration here !</a>\n");
      out.write("        </div>                    \n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("   \n");
      out.write("    \n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("  function cap(){\n");
      out.write("    var alpha = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V'\n");
      out.write("                 ,'W','X','Y','Z','1','2','3','4','5','6','7','8','9','0','a','b','c','d','e','f','g','h','i',\n");
      out.write("                 'j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z', '!','@','#','$','%','^','&','*','+'];\n");
      out.write("                 var a = alpha[Math.floor(Math.random()*71)];\n");
      out.write("                 var b = alpha[Math.floor(Math.random()*71)];\n");
      out.write("                 var c = alpha[Math.floor(Math.random()*71)];\n");
      out.write("                 var d = alpha[Math.floor(Math.random()*71)];\n");
      out.write("                 var e = alpha[Math.floor(Math.random()*71)];\n");
      out.write("                 var f = alpha[Math.floor(Math.random()*71)];\n");
      out.write("\n");
      out.write("                 var final = a+b+c+d+e+f;\n");
      out.write("                 document.getElementById(\"capt\").value=final;\n");
      out.write("               }\n");
      out.write("               function validcap(){\n");
      out.write("                var stg1 = document.getElementById('capt').value;\n");
      out.write("                var stg2 = document.getElementById('textinput').value;\n");
      out.write("                if(stg1==stg2){\n");
      out.write("                  alert(\"login Succesfully\");\n");
      out.write("                  return true;\n");
      out.write("                }else{\n");
      out.write("                  alert(\"Please enter a valid captcha\");\n");
      out.write("                  return false;\n");
      out.write("                }\n");
      out.write("               }\n");
      out.write("</script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\" crossorigin=\"anonymous\"></script>\n");
      out.write("            \n");
      out.write(" \n");
      out.write("    <div class=\"footer\">\n");
      out.write("  <p>Blood Bank Management System\n");
      out.write("      <br>\n");
      out.write("      Made In India &copy; 2021\n");
      out.write("  </p>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
