package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contactus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("         <meta charset=\"UTF-8\">\n");
      out.write("         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("         \n");
      out.write("         <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\"/>\n");
      out.write("         <!--<link rel=\"stylesheet\"href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">-->\n");
      out.write("\n");
      out.write("            <link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\" integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("         \n");
      out.write("        <style>\n");
      out.write("             @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');\n");
      out.write("            #wrapper\n");
      out.write("            {\n");
      out.write("                width:100%;\n");
      out.write("                height: 1200px;\n");
      out.write("                 \n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            #parent\n");
      out.write("            {\n");
      out.write("                width: 100%;\n");
      out.write("                height: 700px;\n");
      out.write("                margin-top: 30px;\n");
      out.write("                \n");
      out.write("            }\n");
      out.write("           \n");
      out.write("            \n");
      out.write("*{\n");
      out.write("  margin: 0px;\n");
      out.write("  padding: 20;\n");
      out.write("  box-sizing: border-box;\n");
      out.write(" // font-family: \"Poppins\" , sans-serif;\n");
      out.write("\n");
      out.write("}\n");
      out.write("body{\n");
      out.write("  min-height: 100vh;\n");
      out.write("  width: 100%;\n");
      out.write("  //background: #c8e8e9;\n");
      out.write("  display: flex;\n");
      out.write("  //align-items:center;\n");
      out.write(" // justify-content: center;\n");
      out.write("}\n");
      out.write(".container{\n");
      out.write("  width: 85%;\n");
      out.write("  background: #fff;\n");
      out.write("  border-radius: 6px;\n");
      out.write("  padding: 20px 60px 30px 60px;\n");
      out.write("  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);\n");
      out.write("  align-items: center;\n");
      out.write("  justify-content: space-between;\n");
      out.write("   margin-right:190px;\n");
      out.write("   margin-top: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container .content{\n");
      out.write("   display: flex;\n");
      out.write("  \n");
      out.write("   align: center;\n");
      out.write("  \n");
      out.write("}\n");
      out.write(".container .content .left-side{\n");
      out.write("  width: 20%;\n");
      out.write("  height: 100%;\n");
      out.write("  display: flex;\n");
      out.write("  flex-direction: column;\n");
      out.write("  align-items: center;\n");
      out.write("  //justify-content: center;\n");
      out.write("  margin-top: 15px;\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write(".content .left-side::before{\n");
      out.write("  content: '';\n");
      out.write("  position: absolute;\n");
      out.write("  height: 70%;\n");
      out.write("  width: 2px;\n");
      out.write("  right: -15px;\n");
      out.write("  top: 50%;\n");
      out.write("  transform: translateY(-50%);\n");
      out.write("  background: red;\n");
      out.write("}\n");
      out.write(".content .left-side .details{\n");
      out.write("  margin: 14px;\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write(".content .left-side .details i{\n");
      out.write("  font-size: 30px;\n");
      out.write("  color: red;\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("}\n");
      out.write(".content .left-side .details .topic{\n");
      out.write("  font-size: 18px;\n");
      out.write("  font-weight: 500;\n");
      out.write("}\n");
      out.write(".content .left-side .details .text-one,\n");
      out.write(".content .left-side .details .text-two{\n");
      out.write("  font-size: 14px;\n");
      out.write("  color: gray;\n");
      out.write("}\n");
      out.write(".container .content .right-side{\n");
      out.write("  width: 75%;\n");
      out.write("  margin-left: 75px;\n");
      out.write("}\n");
      out.write(".content .right-side .topic-text{\n");
      out.write("  font-size: 23px;\n");
      out.write("  font-weight: 600;\n");
      out.write("  color: red;\n");
      out.write("}\n");
      out.write(".right-side .input-box{\n");
      out.write("  height: 50px;\n");
      out.write("  width: 100%;\n");
      out.write("  margin: 12px 0;\n");
      out.write("}\n");
      out.write(".right-side .input-box input,\n");
      out.write(".right-side .input-box textarea{\n");
      out.write("  height: 100%;\n");
      out.write("  width: 100%;\n");
      out.write("  border: none;\n");
      out.write("  outline: none;\n");
      out.write("  font-size: 16px;\n");
      out.write("  background: lightgrey;\n");
      out.write("  border-radius: 6px;\n");
      out.write("  padding: 0 15px;\n");
      out.write("  resize: none;\n");
      out.write("}\n");
      out.write(".right-side .message-box{\n");
      out.write("  min-height: 110px;\n");
      out.write("}\n");
      out.write(".right-side .input-box textarea{\n");
      out.write("  padding-top: 6px;\n");
      out.write("}\n");
      out.write(".right-side .button{\n");
      out.write("  display: inline-block;\n");
      out.write("  margin-top: 12px;\n");
      out.write("}\n");
      out.write(".right-side .button input[type=\"submit\"]{\n");
      out.write("  color: #fff;\n");
      out.write("  font-size: 18px;\n");
      out.write("  outline: none;\n");
      out.write("  border: none;\n");
      out.write("  padding: 8px 16px;\n");
      out.write("  border-radius: 6px;\n");
      out.write("  background: red;\n");
      out.write("  cursor: pointer;\n");
      out.write("  transition: all 0.3s ease;\n");
      out.write("}\n");
      out.write(".button input[type=\"submit\"]:hover{\n");
      out.write("  background: green;\n");
      out.write("}\n");
      out.write("\n");
      out.write("           </style>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light fixed-top bg-danger\">\n");
      out.write("        <a style=\"color:white;\" class=\"navbar-brand\" href=\"/\"><i class=\"fab fa-gratipay\"></i>&nbsp;<font face = \"Comic sans MS\" size =\"4\">Blood Bank Management System</font></a>\n");
      out.write("        \n");
      out.write("      \n");
      out.write("        <div class=\"navbar-collapse collapse w-100 order-3 dual-collapse2\">\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" style=\"color: white;\" href=\"index.jsp\">Logout &nbsp; <i class=\"fas fa-sign-out-alt\"></i></a>\n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("<br>\n");
      out.write("              <div id=\"parent\">\n");
      out.write("                  <div class=\"container\" style=\"align:center\">\n");
      out.write("    <div class=\"content\" >\n");
      out.write("      <div class=\"left-side\">\n");
      out.write("        <div class=\"address details\">\n");
      out.write("          <i class=\"fas fa-map-marker-alt\"></i>\n");
      out.write("          <div class=\"topic\">Address</div>\n");
      out.write("          <div class=\"text-one\">City Hospital Lucknow</div>\n");
      out.write("          <div class=\"text-two\">Sushma Hospital Faizabad Road</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"phone details\">\n");
      out.write("          <i class=\"fas fa-phone-alt\"></i>\n");
      out.write("          <div class=\"topic\">Phone</div>\n");
      out.write("          <div class=\"text-one\">7860239897,&nbsp 8303849695</div>\n");
      out.write("          <div class=\"text-two\">9369300849,&nbsp 9621196285</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"email details\">\n");
      out.write("          <i class=\"fas fa-envelope\"></i>\n");
      out.write("          <div class=\"topic\">Email</div>\n");
      out.write("          <div class=\"text-one\">bloodbank@gmail.com</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"right-side\">\n");
      out.write("          <div class=\"topic-text\"><h3>Send us a message.....</h3></div>\n");
      out.write("        <p> (If you have any types of quries related to Blood, you can send  message from here. It's our pleasure to help you!)</p>\n");
      out.write("      <form action=\"contactAction.jsp\" method=\"post\">\n");
      out.write("        <div class=\"input-box\">\n");
      out.write("          <input type=\"text\" name=\"name\" placeholder=\"Enter your name\">\n");
      out.write("        </div>\n");
      out.write("          \n");
      out.write("      \n");
      out.write("        <div class=\"input-box\">\n");
      out.write("          <input type=\"text\" name=\"address\" placeholder=\"Enter your address\">\n");
      out.write("        </div>\n");
      out.write("         <div class=\"input-box\">\n");
      out.write("          <input type=\"text\" name=\"contactno\" placeholder=\"Enter contact no\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"input-box\">\n");
      out.write("          <input type=\"email\" name=\"emailaddress\" placeholder=\"Enter email address\">\n");
      out.write("        </div>\n");
      out.write("          \n");
      out.write("        <div class=\"input-box message-box\">\n");
      out.write("            <input type=\"text\" name=\"enquirytext\" placeholder=\"Enter enquiry text\">\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("        <div class=\"button\">\n");
      out.write("          <input type=\"submit\" value=\"Send Now\" >\n");
      out.write("        </div>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
